spring:
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
 rabbitmq:
    host: 192.168.25.138
    username: guest
    password: guest
    port: 5672
env:
  test
girl:
  name: Gakki
  age: 2511
