spring:
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=fals
  redis:
    host: 192.168.25.138
    port: 6379
env:
  dev
